### ISSUE TITLE
Missing dependency in the appimage

### ISSUE THREAD

**Issue by r-ps** [iohzrd/tauri-svelte#1]
On arch linux I needed to install webkit2gtk in order to launch identia

**Comment by iohzrd** [comment]
I'm not sure if this is an issue with Tauri's bundler (seeing that tauri is still quite young) or if this will be permanent dependency. I'll look into it further and post here. Thanks for the comment and sorry for the delay.

**Comment by FabianLars** [comment]
@iohzrd This was (supposedly) fixed with the first release candidate in february, see https://togithub.com/tauri-apps/tauri/pull/2940

**Comment by iohzrd** [comment]
I was hoping that would be the case. Thanks.
